parrot = "Norwegian Blue"
print(parrot)
print(parrot[0])
print(parrot[3])
print('The length of the above string is:', len(parrot))
print(' the -1 position','\n', parrot[-1])
print('0 through 6','\n', parrot[0:6])
print('shorthand for 0->6','\n', parrot[:6])
print('position 6 to the end','\n', parrot[6:])
print('pos -4 to -2','\n', parrot[-4:-2])
print(parrot[0:6:2])
print(parrot[0:6:3])
